comp = float(input('digite o comprimento ou altura do seu quadrado: '))
area_quad = (comp*comp)
result = (area_quad*2)
print ('A area do quadrado é: ',area_quad)
print ("O dobro da area do seu quadrado é: ", result)
